name: Sync Website to S3

on:
  push:
    paths:
      - 'web/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Sync Files to S3
      run: |
        aws s3 sync ./web s3://new-timmy-7.serverless.my.id --acl public-read --delete

    # Activate on production when TTL is set, currently set to off
    # - name: Invalidate CloudFront Cache
    #   run: |
    #     aws cloudfront create-invalidation \
    #       --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
    #       --paths "/*"
